"""PART : 01
Q:11 Write a program that evaluates if an input number is prime.

"""
# NOTE: this code is generated by 'chat gpt' but i learnd what logic in this program working 

num = int(input("Enter a number: "))

if num > 1:# this line if num is greater than 1 then run the body program of this line other wise print(f"{num} is not a prime number.")  
    if num == 2 or num == 3: # this line check if num equl to 2 or 3 print its prime NO.
        print(f"{num} is a prime number.")
    elif num % 2 == 0 or num % 3 == 0: # this line check if num divided by 2 or 3 and its reminder is 0  print its not prime NO.
        print(f"{num} is not a prime number.")
    elif num == 5 or num % 5 == 0: # this line check if num equl to 5 or divide by 5 and its reminder is 0 print its notprime NO.
        print(f"{num} is not a prime number.")
    else: 
        print(f"{num} is a prime number.")
else:
    print(f"{num} is not a prime number.")
